# -*- coding: utf-8 -*-
"""INF1344 Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M241JLOx3u03aJ_AOy4FgmB-fIKnPOAS
"""

# note: this part of the code performed in Google Colab
import pandas as pd
import scipy as sp 
from scipy import stats

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['Goodreads_Amazon Bestseller data - books_WORKHERE.csv']))

# preview the data set
df

"""Step 1: Store the fiction and nonfiction books in separate dataframes"""

# Creates a fiction dataframe
sep1 = df.groupby(df.Genre)
fict = sep1.get_group('Fiction')
fict

# Creates a nonfiction dataframe
sep2 = df.groupby(df.Genre)
nonfict = sep1.get_group('Nonfiction')
nonfict

# Since there are more nonfiction entries, we reduced the nonfiction dataframe so that both sample sizes are the same
nonfict = nonfict.iloc[:139]
nonfict

"""We will perform 2 sample t-test to estimate the difference between. population means

- Based on previous studies, let's test whether or not the average Goodreads rating for Fiction books are higher than Nonfiction books.

Step 1: Null and Alternative Hypotheses

- Ho: u1 = u2
- H1: u1 > u2

Step 2: Select a Confidence Level
- 95% confidence interval 
- alpha = 0.05

- note: t-alpha = 1.66
- degrees of freedom = 100

Step 3: Compute the test statistic

- number of books in each: n1 and n2
"""

n1 = fict['Title'].count()
n2 = nonfict['Title'].count()

print(n1)
print(n2)

"""- Average scores: xbar1 and xbar2 """

avg_nfict_rating = nonfict.mean(axis = 0)
avg_fict_rating = fict.mean(axis=0)

print(avg_nfict_rating)
print(avg_fict_rating)

"""- Sample standard deviations: s1 and s2"""

s1 = fict['GR_rating'].std()
s1

s2 = nonfict['GR_rating'].std()
s2

fict_ar = fict['GR_rating'].to_numpy()
fict_ar

nonfict_ar = nonfict["GR_rating"].to_numpy() 
nonfict_ar

stats.ttest_ind(fict_ar, nonfict_ar, nan_policy = 'omit')

"""- CONCLUSION: WE REJECT THE NULL HYPOTHESIS SINCE IT IS IN THE CRITICAL REGION.

"""